In [31]:
import pandas as pd
import numpy as np

In [32]:
df=pd.read_csv("updated_file.csv")
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,01/01/2021,06/01/2021,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2021
1,IN-2011-47883,01/01/2021,08/01/2021,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2021
2,HU-2011-1220,01/01/2021,05/01/2021,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2021
3,IT-2011-3647632,01/01/2021,05/01/2021,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2021
4,IN-2011-47883,01/01/2021,08/01/2021,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2021

In [33]:
df.describe(include="all")

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
count,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,...,51290,51290,51290,51290,51290.000000,51290.000000,51290.000000,51290.000000,51290,51290.000000
unique,25035,1429,1463,4,795,3,1094,147,7,13,...,3,17,3788,2246,NaN,NaN,NaN,NaN,4,NaN
top,CA-2014-100111,18/06/2024,22/11/2024,Standard Class,Muhammed Yedwab,Consumer,California,United States,APAC,Central,...,Office Supplies,Binders,Staples,13,NaN,NaN,NaN,NaN,Medium,NaN
freq,14,135,130,30775,108,26518,2001,9994,11002,11117,...,31273,6152,227,589,NaN,NaN,NaN,NaN,29433,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.476545,0.142908,28.641740,26.375915,NaN,2022.777208
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.278766,0.212280,174.424113,57.296804,NaN,1.098931
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.000000,0.000000,-6599.978000,0.000000,NaN,2021.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.000000,0.000000,0.000000,2.610000,NaN,2022.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.000000,0.000000,9.240000,7.790000,NaN,2023.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.000000,0.200000,36.810000,24.450000,NaN,2024.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,14.000000,0.850000,8399.976000,933.570000,NaN,2024.000000

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  str
 2   ship_date       51290 non-null  str
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  str
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), str(16)
memory usage: 16.6 MB

In [35]:
df.product_id

0        OFF-TEN-10000025
1         OFF-SU-10000618
2        OFF-TEN-10001585
3         OFF-PA-10001492
4         FUR-FU-10003447
               ...
51285     OFF-BI-10002103
51286    OFF-WIL-10001069
51287     OFF-LA-10004182
51288     OFF-LA-10000413
51289     OFF-FA-10003472
Name: product_id, Length: 51290, dtype: str

In [36]:
df

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,01/01/2021,06/01/2021,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.1400,35.46,Medium,2021
1,IN-2011-47883,01/01/2021,08/01/2021,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.0360,9.72,Medium,2021
2,HU-2011-1220,01/01/2021,05/01/2021,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.6400,8.17,High,2021
3,IT-2011-3647632,01/01/2021,05/01/2021,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.0550,4.82,High,2021
4,IN-2011-47883,01/01/2021,08/01/2021,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.7700,4.70,Medium,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,CA-2014-115427,31/12/2024,04/01/2025,Standard Class,Erica Bern,Corporate,California,United States,US,West,...,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",14,2,0.2,4.5188,0.89,Medium,2024
51286,MO-2014-2560,31/12/2024,05/01/2025,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,...,Office Supplies,Binders,"Wilson Jones Hole Reinforcements, Clear",4,1,0.0,0.4200,0.49,Medium,2024
51287,MX-2014-110527,31/12/2024,02/01/2025,Second Class,Charlotte Melton,Consumer,Managua,Nicaragua,LATAM,Central,...,Office Supplies,Labels,"Hon Color Coded Labels, 5000 Label Set",26,3,0.0,12.3600,0.35,Medium,2024
51288,MX-2014-114783,31/12/2024,06/01/2025,Standard Class,Tamara Dahlen,Consumer,Chihuahua,Mexico,LATAM,North,...,Office Supplies,Labels,"Hon Legal Exhibit Labels, Alphabetical",7,1,0.0,0.5600,0.20,Medium,2024
51289,CA-2014-156720,31/12/2024,04/01/2025,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,...,Office Supplies,Fasteners,Bagged Rubber Bands,3,3,0.2,-0.6048,0.17,Medium,2024

In [37]:
df['profit'] = df['profit'].round(2)
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,01/01/2021,06/01/2021,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.14,35.46,Medium,2021
1,IN-2011-47883,01/01/2021,08/01/2021,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.04,9.72,Medium,2021
2,HU-2011-1220,01/01/2021,05/01/2021,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.64,8.17,High,2021
3,IT-2011-3647632,01/01/2021,05/01/2021,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.06,4.82,High,2021
4,IN-2011-47883,01/01/2021,08/01/2021,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.77,4.70,Medium,2021

In [38]:
df.order_date=pd.to_datetime(df.order_date,format="%d/%m/%Y")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  datetime64[us]
 2   ship_date       51290 non-null  str
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  str
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
dtypes: datetime64[us](1), float64(3), int64(2), str(15)
memory usage: 16.1 MB

In [39]:
df.ship_date=pd.to_datetime(df.ship_date,format="%d/%m/%Y")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  datetime64[us]
 2   ship_date       51290 non-null  datetime64[us]
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  str
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
dtypes: datetime64[us](2), float64(3), int64(2), str(14)
memory usage: 15.6 MB

In [40]:
df.sales=pd.to_numeric(df['sales'].str.replace(',', ''), errors='coerce')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  datetime64[us]
 2   ship_date       51290 non-null  datetime64[us]
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  int64
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 15.5 MB

In [41]:
df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [42]:
df.isna().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [43]:
df["order_month"] = df["order_date"].dt.month
df["order_day"] = df["order_date"].dt.day
df["order_year"] = df["order_date"].dt.year
df["ship_month"] = df["ship_date"].dt.month
df["ship_day"]= df["ship_date"].dt.day 
df["ship_year"]= df["ship_date"].dt.year
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  datetime64[us]
 2   ship_date       51290 non-null  datetime64[us]
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  int64
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
 21  order_month     51290 non-null  int32
 22  order_day       51290 non-null  int32
 23  order_year      51290 non-null  int32
 24  ship_month      51290 non-null  int32
 25  ship_day        51290 non-null  int32
 26  ship_year       51290 non-null  int32
dtypes: datetime64[us](2), float64(3), int32(6), int64(3), str(13)
memory usage: 16.7 MB

In [44]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,profit,shipping_cost,order_priority,year,order_month,order_day,order_year,ship_month,ship_day,ship_year
0,AG-2011-2040,2021-01-01,2021-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,106.14,35.46,Medium,2021,1,1,2021,1,6,2021
1,IN-2011-47883,2021-01-01,2021-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,36.04,9.72,Medium,2021,1,1,2021,1,8,2021
2,HU-2011-1220,2021-01-01,2021-01-05,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,29.64,8.17,High,2021,1,1,2021,1,5,2021
3,IT-2011-3647632,2021-01-01,2021-01-05,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,-26.06,4.82,High,2021,1,1,2021,1,5,2021
4,IN-2011-47883,2021-01-01,2021-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,37.77,4.70,Medium,2021,1,1,2021,1,8,2021

In [45]:
df.drop(["order_date","ship_date"], axis=1, inplace=True)